name: fraud-detection-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - lightgbm
  - matplotlib
  - mlflow
  - joblib
  - pip
  - pip:
      - azureml-core
      - azureml-defaults
      - azureml-mlflow
      - azure-ai-ml





